# This file was generated by GoReleaser. DO NOT EDIT.
class Spell < Formula
  desc "spell word(s) using a spelling alphabet."
  homepage ""
  version "0.3.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/simonnagl/spell/releases/download/v0.3.1/spell_0.3.1_Darwin_x86_64.tar.gz"
    sha256 "64c4bf33b949c66da95f02a9b61392ec6048a4c5889b57d4fe6e420ab955ad3c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/simonnagl/spell/releases/download/v0.3.1/spell_0.3.1_Linux_x86_64.tar.gz"
      sha256 "36cc097715d2a28d19e64126c55db603d30fa83cf9c45280163a4eff118a128f"
    end
  end

  def install
    bin.install "spell"
  end

  def caveats; <<~EOS
    Check spell -h
  EOS
  end
end
